# Generated by Django 2.2.10 on 2020-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='产品名称')),
                ('devconfig', models.TextField(blank=True, null=True, verbose_name='开发环境配置')),
                ('testconfig', models.TextField(blank=True, null=True, verbose_name='测试环境配置')),
                ('prodconfig', models.TextField(blank=True, null=True, verbose_name='生产环境配置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目和配置',
                'verbose_name_plural': '项目和配置',
            },
        ),
    ]
