# Generated by Django 2.2.11 on 2020-04-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=200, unique=True)),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='product.Product')),
            ],
            options={
                'verbose_name_plural': '用例',
                'verbose_name': '用例',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=200, unique=True)),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name_plural': '页面',
                'verbose_name': '页面',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementname', models.CharField(max_length=200)),
                ('targeting', models.CharField(choices=[('1', 'id'), ('2', 'name'), ('3', 'class'), ('4', 'link_text'), ('5', 'tag_name'), ('6', 'css_selector'), ('7', 'xpath'), ('0', 'coordinate')], default=1, max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Page')),
            ],
            options={
                'verbose_name_plural': '元素',
                'verbose_name': '元素',
            },
        ),
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='序号')),
                ('action', models.CharField(choices=[('1', 'click'), ('2', 'sendstr'), ('3', 'moveto')], max_length=200)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('assertdata', models.CharField(blank=True, max_length=200, null=True)),
                ('extract', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='webtest.Case')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webtest.Element')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Page')),
            ],
            options={
                'verbose_name_plural': '用例步骤',
                'verbose_name': '用例步骤',
            },
        ),
    ]
