# Generated by Django 2.2.10 on 2020-04-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apicase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路径')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='post', max_length=200, verbose_name='请求方法')),
                ('param', models.TextField(blank=True, null=True, verbose_name='请求参数和值,parametrize表示参数化')),
                ('parametrize', models.TextField(blank=True, null=True, verbose_name='参数化')),
                ('expect', models.CharField(max_length=200, verbose_name='预期结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apicase', to='product.Product')),
            ],
            options={
                'verbose_name': '单一接口用例',
                'verbose_name_plural': '单一接口用例',
            },
        ),
    ]
