# Generated by Django 2.2.10 on 2020-04-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='path')),
                ('headers', models.TextField(max_length=800, null=True, verbose_name='请求头')),
                ('param', models.TextField(blank=True, max_length=800, null=True, verbose_name='请求参数值')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('expect', models.TextField(max_length=200, verbose_name='预期结果')),
                ('extract', models.TextField(blank=True, max_length=200, null=True, verbose_name='提取数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='product.Product')),
            ],
            options={
                'verbose_name': '流程场景接口',
                'verbose_name_plural': '流程场景接口',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='product.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '流程场景用例',
                'verbose_name_plural': '流程场景用例',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='序号')),
                ('desc', models.TextField(verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Api', verbose_name='接口')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='apitest.Process', verbose_name='流程用例')),
            ],
            options={
                'verbose_name': '关联用例和接口',
                'verbose_name_plural': '关联用例和接口',
            },
        ),
    ]
