# Generated by Django 2.2.10 on 2020-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_api_process_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='headers',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='请求头'),
        ),
    ]
