# Generated by Django 2.2.11 on 2020-05-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEXTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.SmallIntegerField(choices=[(1, '限价买单不成交'), (2, '限价买单成交'), (3, '市价买单成交'), (4, '限价卖单不成交'), (5, '限价卖单成交'), (6, '市价卖单成交')], verbose_name='用例类型')),
                ('symbol', models.CharField(max_length=100, verbose_name='交易对')),
                ('status', models.BooleanField(verbose_name='是否通过')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'DEX测试结果',
            },
        ),
    ]
